version: '3.1'

networks:
  wod:

services:
  wod-app:
    container_name: lumen
    build:
      context: .
      dockerfile: .docker/php.Dockerfile
    image: 'php8-lumen'
    extra_hosts:
        - "host.docker.internal:host-gateway"
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/app
    networks:
      - wod

  wod-db:
    image: mariadb:lts
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'wod_app'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: "app_wod"
    networks:
      - wod

  wod-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: wod-db
      PMA_USER: root
      PMA_PASSWORD: "app_wod"
    ports:
      - "8081:80"
    depends_on:
      - wod-db
    networks:
      - wod